version: "3"

networks:
  app_network:
    driver: bridge

services:
  web:
    container_name: cartelz-web
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 53015:3000
    networks:
      - app_network
    env_file:
      - .env.local
